# Download Node.js image from Docker Hub
FROM node:latest

# Create directory for container
WORKDIR /api

# Copy files and install dependencies
COPY package*.json ./
RUN npm install
COPY . .
RUN npm uninstall bcrypt
RUN npm install bcrypt

# Environment variables
ENV ENVIRONMENT dev
ENV HOSTNAME localhost
ENV PORT 3001
ENV JWT_SECRET dev_secret
ENV DB_HOSTNAME db
ENV DB_USER root
ENV DB_DBNAME omnistudy
ENV DB_PORT 3306
ENV DB_PASSWORD test
ENV PROJECT_ID omnistudy-422217
ENV BUCKET_NAME omnibucket-dev
ENV AI_BASE_URL http://ai:5001

# Expose port and run the app
EXPOSE 3001
CMD ["npm", "run", "dev"]