# Download Node.js image from Docker Hub
FROM node:latest

# Create directory for container
WORKDIR /api

# Copy files and install dependencies
COPY package*.json ./
RUN npm install
COPY . .

# Environment variables
ENV ENVIRONMENT dev
ENV HOSTNAME localhost
ENV PORT 3001
ENV JWT_SECRET dev_secret
ENV DB_HOSTNAME db
ENV DB_USER root
ENV DB_DBNAME omnistudy
ENV DB_PORT 3306
ENV DB_PASSWORD test
ENV S3_BUCKET omnistudy
ENV S3_REGION us-west-2

# Expose port and run the app
EXPOSE 3001
CMD ["npm", "run", "dev"]