# Download Node.js image from Docker Hub
FROM node:20-alpine

# Create directory for container
WORKDIR /api

# Copy files and install dependencies
COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build

# Environment variables
ENV ENVIRONMENT staging
ENV HOSTNAME http://staging-api.omnistudy.io
ENV PORT 80
ENV JWT_SECRET staging_secret
ENV BUCKET_NAME omnibucket-staging

# Expose port and run the app
EXPOSE 80
CMD ["npm", "run", "start"]